// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxdaREuz3BqQJaSBfFqxDRfadfvNK3eM',
    appId: '1:517388722376:web:e82754556e48e9a0f705fd',
    messagingSenderId: '517388722376',
    projectId: 'get-work-48682',
    authDomain: 'get-work-48682.firebaseapp.com',
    storageBucket: 'get-work-48682.firebasestorage.app',
    measurementId: 'G-B8F44R7V0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkDt1uE9fABOcxhdl3ziesHwkvHYpTqqc',
    appId: '1:517388722376:android:563014665f449b70f705fd',
    messagingSenderId: '517388722376',
    projectId: 'get-work-48682',
    storageBucket: 'get-work-48682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFgTyDtTtxwmd-msjjyF85exb9Wc_Q0ok',
    appId: '1:517388722376:ios:d1d4eea86ce4f160f705fd',
    messagingSenderId: '517388722376',
    projectId: 'get-work-48682',
    storageBucket: 'get-work-48682.firebasestorage.app',
    iosBundleId: 'com.example.getWorkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFgTyDtTtxwmd-msjjyF85exb9Wc_Q0ok',
    appId: '1:517388722376:ios:d1d4eea86ce4f160f705fd',
    messagingSenderId: '517388722376',
    projectId: 'get-work-48682',
    storageBucket: 'get-work-48682.firebasestorage.app',
    iosBundleId: 'com.example.getWorkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKxdaREuz3BqQJaSBfFqxDRfadfvNK3eM',
    appId: '1:517388722376:web:aa450b29ebdb514cf705fd',
    messagingSenderId: '517388722376',
    projectId: 'get-work-48682',
    authDomain: 'get-work-48682.firebaseapp.com',
    storageBucket: 'get-work-48682.firebasestorage.app',
    measurementId: 'G-K0VVP3CV50',
  );
}
